### ISSUE TITLE
Add Flip module

### ISSUE THREAD

**Issue by jwosty** [Zaid-Ajaj/Fable.Mocha#16]
Adding a Flip module to imitate Expecto.Flip would be a nice-to-have feature.

**Comment by Zaid-Ajaj** [comment]
Hello there @jwosty, 

I haven't used used `Flip` before and looking at the docs, I am not sure I not I get what it is supposed to do 😅 can you briefly explain to me what the expected behavior is? Thanks!

> To be honest, I am a little hesitant to supporting more Expecto constructs because I am not be able to properly support the Mocha API which has higher priority for this library

**Comment by jwosty** [comment]
Sure, the Flip module just reorders arguments (nothing more than that) to make it a little nicer to use with the pipe operator. For example:

```fsharp
let actual = 2+2
let expected = 4
actual |> Expect.equal "2+2=4" expected
```

I've just written pretty much the whole thing for my own project since my tests were already using Flip, and this is what I came up with (you'll see this also references some of my own extension functions, like Fable.Mocha.Expect.sequenceEqual):

```fsharp
module Fable.Mocha.Flip
open Fable.Mocha

module Expect =
    let equal (msg: string) (expected: 'a) (actual: 'a) = Expect.equal actual expected msg
    let notEqual (msg: string) (expected: 'a) (actual: 'a) = Expect.notEqual actual expected msg
    let isTrue (msg: string) (actual: bool) = Expect.isTrue actual msg
    let isFalse (msg: string) (actual: bool) = Expect.isFalse actual msg
    let sequenceEqual (msg: string) (expected: 'a seq) (actual: 'a seq) =
        let actual' = Seq.toArray actual
        let expected' = Seq.toArray expected
        Expect.sequenceEqual actual' expected' msg
    let throws (msg: string) (f: unit -> unit) = Expect.throws f msg
    let throwsT<'TExn> (msg: string) (f: unit -> unit) = Expect.throwsT f msg
```

**Comment by Zaid-Ajaj** [comment]
Thanks a lot for the explaination @jwosty. Unfortunately, I am afraid that this is one of those details of Expecto that I would rather not include in the library since it is very easy to add from user's point of view (including your workaround). I would like to keep the absolute minimum of support for Expecto's API so that it doesn't conflict with Mocha in the long run. (It is already very complicated to make tests behave well in all runners).

**Comment by jwosty** [comment]
OK, thank you for the perspective. I appreciate it.

**Comment by Zaid-Ajaj** [comment]
Thank you for the kind words and for understanding my reasoning :pray:
