### ISSUE TITLE
Arguments order of Expect.equal is flipped between Expecto and Fable.Mocha

### ISSUE THREAD

**Issue by MangelMaxime** [Zaid-Ajaj/Fable.Mocha#17]
Hello,

I am finally deciding to use this library instead of re-write the binding in each of my library but I am facing a problem.

![image](https://user-images.githubusercontent.com/4760796/82491715-4db33580-9ae5-11ea-8e84-8a1871a7b2c7.png)

![image](https://user-images.githubusercontent.com/4760796/82491732-5441ad00-9ae5-11ea-82f7-00e19d75d03e.png)

The arguments order of Expect.equal is flipped between Expecto and Fable.Mocha

A workaround is to use this kind of code in the user code:

```fs
#if FABLE_COMPILER
let inline equal expected actual: unit =
    Expect.equal expected actual ""
#else
let inline equal expected actual: unit =
    Expect.equal actual expected ""
#endif
```

But it kind of lose a bit of the interest of not writing the wrapper in each project ^^

**Comment by Zaid-Ajaj** [comment]
Hi Maxime, I think at this point I have flipped the order of the arguments three times already so a fourth time will bring me back to zero :joy: to be honest, this isn't really a problem because the error messages you get are still correct "expect X but got Y", right?

**Comment by MangelMaxime** [comment]
Yes, I know the order of the arguments is a nightmare...

By looking at the documentation or source of several assertion libraries the current order of the arguments is not consistent with them.

> Mocha allows you to use any assertion library you wish

So I took a look at several of them

[Chaijs](https://www.chaijs.com/api/assert/)

![image](https://user-images.githubusercontent.com/4760796/82544081-d917df80-9b54-11ea-9687-3075ac9397cc.png)

[Node.js](https://nodejs.org/api/assert.html#assert_assert_equal_actual_expected_message)

![image](https://user-images.githubusercontent.com/4760796/82544118-ea60ec00-9b54-11ea-8770-2e0a4b9a85f2.png)

[Should.js](http://shouldjs.github.io/#should-equal)

![image](https://user-images.githubusercontent.com/4760796/82544145-f64cae00-9b54-11ea-8cc3-1d87f3e714f3.png)

---------

[Expecto](https://github.com/haf/expecto/blob/master/Expecto/Expect.fs#L345)

![image](https://user-images.githubusercontent.com/4760796/82544201-0ebcc880-9b55-11ea-959a-d4db034dbb37.png)

It seems like most (because I didn't check all the possible testing libraries^^) use the order `actual expected`.

By looking at the implementation of [Fable.Mocha](https://github.com/Zaid-Ajaj/Fable.Mocha/blob/master/src/Mocha.fs#L42-L59) there is several things we can see.

```fs
[<RequireQualifiedAccess>]
module Expect =
    let inline equal (expected: 'a) (actual: 'a)  msg  : unit =
        if actual = expected || not (Env.isBrowser()) then
            Assert.AreEqual(actual, expected, msg)
        else
            let valueType = actual.GetType()
            let primitiveTypes = [ typeof<int>; typeof<bool>; typeof<double>; typeof<string>; typeof<decimal>; typeof<Guid> ]
            let errorMsg =
                if List.contains valueType primitiveTypes then
                    sprintf "<span style='color:black'>Expected:</span> <br /><div style='margin-left:20px; color:crimson'>%s</div><br /><span style='color:black'>Actual:</span> </br ><div style='margin-left:20px;color:crimson'>%s</div><br /><span style='color:black'>Message:</span> </br ><div style='margin-left:20px; color:crimson'>%s</div>" (string expected) (string actual) msg
                else
                    sprintf "<span style='color:black'>Expected:</span> <br /><div style='margin-left:20px; color:crimson'>%A</div><br /><span style='color:black'>Actual:</span> </br ><div style='margin-left:20px;color:crimson'>%A</div><br /><span style='color:black'>Message:</span> </br ><div style='margin-left:20px; color:crimson'>%s</div>" expected actual msg

            raise (Exception(errorMsg))

    let notEqual actual expected msg  : unit =
        Assert.NotEqual(actual, expected, msg)
```

1. The argument order between `Expect.equal` and `Expect.notEqual` is not consistent
2. Fable.Mocha is flipping the argument order internally when calling `Assert.AreEqual` which is probably why it seems to report them correctly in the output even if the exposed interface is not following the others "standard"

If we use only Fable.Mocha for testing them it is probably not a big deal even if the non-consistent order of the arguments between `equal` and `notEqual` is a problem.

But the problem is that if we try to write a test project compatible with both Fable.Mocha and Expecto then just doing what the [readme](https://github.com/Zaid-Ajaj/Fable.Mocha#running-the-tests-on-dotnet-with-expecto) say is not enough.

**Test code**
```fs
equal "Maxime" "Zaid"
```

**Fable.Mocha**

![image](https://user-images.githubusercontent.com/4760796/82546267-26498080-9b58-11ea-9f14-5f38ffc658db.png)

**Expecto**

![image](https://user-images.githubusercontent.com/4760796/82546386-5133d480-9b58-11ea-85fc-59d4d0c9b0f6.png)

And so the user needs to add some code to create his own bridge between the two libraries which is prone to errors.

Using something like:

```fs
#if FABLE_COMPILER
let inline equal expected actual message : unit =
    Expect.equal expected actual message
#else
let inline equal expected actual message: unit =
    Expect.equal actual expected message
#endif
```

As you mentioned before making any change we need to be 200% sure of what we are doing and if we are to make it, it is definitly a breaking change and needs a major release.

**Comment by Zaid-Ajaj** [comment]
@MangelMaxime tbh I personally don't mind it at all that the arguments are flipped, after all: x = y is the same as y = x but it just means you get a different error message and that can be confusing! Can you please send a PR with the fix? 

I am not entirely sure this fix is a breaking change 🤔 after all the tests will continue to pass (or fail) regardless of the order of arguments.

**Comment by MangelMaxime** [comment]
Indeed, x = y and y = x but that's not what is causing the problem as you said.

For me, they are breaking changes because it means that in order to have the right report people needs to swap the order of their arguments. But the decision is on you :)

> Can you please send a PR with the fix?

Sure, I will and I will also check what happens when using the browser standalone runner. But in theory, the environnement you are running your test in is just a kind of viewer so that's should be fine.
