### ISSUE TITLE
Relax FSharp.Core dependency?

### ISSUE THREAD

**Issue by MangelMaxime** [Zaid-Ajaj/Fable.Mocha#19]
Hello,

in a similar way as it has been done for [Feliz](https://github.com/Zaid-Ajaj/Feliz/commit/aa0a742237fd8329cb942f192dfa48200e2f81c4) is it possible to relax the dependency over FSharp.Core?

**Comment by MangelMaxime** [comment]
In fact, I am asking that because I don't really know why I get a warning about a downgrade to FSharp.Core 4.7.0 instead of 4.7.1.

Do you know how is FSharp.Core version determined when not present in an fsproj?

**Comment by Zaid-Ajaj** [comment]
Hi Maxime, it should be easy to do, I will get to it ASAP. 

> Do you know how is FSharp.Core version determined when not present in an fsproj?

I *think* it depends on the currently used SDK, latest one uses a more recent version of F# core

**Comment by MangelMaxime** [comment]
Ok thank you and I have the same feeling as you.

*Note: I never had the problem because I was using paket with a redirection but I am trying to simplify my repositories by using `nuget` instead of  `paket` and `npm` instead of  `yarn`.*

**Comment by Zaid-Ajaj** [comment]
Published Fable.Mocha v2.9.1 which should have a relaxed and chill version constraint on FSharp.Core :rocket: 

>  I am trying to simplify my repositories by using nuget instead of paket and npm instead of yarn.

Happy to hear that 😍
