### ISSUE TITLE
Add instructions to run Mocha on a web page?

### ISSUE THREAD

**Issue by alfonsogarciacaro** [Zaid-Ajaj/Fable.Mocha#2]
If we are to recommend this for testing Fable apps, maybe we should include instructions to run the tests in a web, as some people may prefer that.

**Comment by Zaid-Ajaj** [comment]
Sure thing! I will write some docs ;)

**Comment by Zaid-Ajaj** [comment]
Done! See the updated README where the user can use the same code to run tests both in node.js *and* the browser! The library now detects if it is running inside the browser, if that is the case, it ignores mocha stuff altogether and runs the *built-in* test runner. 

The UI is a bit simplistic but very much usuable
