### ISSUE TITLE
Expect.throws not implemented?

### ISSUE THREAD

**Issue by pw242** [Zaid-Ajaj/Fable.Mocha#37]
Expecto supports `Expect.throws` but Mocha doesn't recognise this. JavaScript supports exceptions so presumably this is a valid test case? Am I doing it wrong or is this not implemented yet?
```
testCase "deleteItem out of range" <| fun _ ->
    Expect.throws (fun _ -> testData |> Array.deleteItem 5 |> ignore) ""
```

**Comment by Linschlager** [comment]
Hi @pw242 

I actually implemented this functionality in https://github.com/Zaid-Ajaj/Fable.Mocha/pull/35, It should now be available on nuget starting with version 2.11
