### ISSUE TITLE
MochaPuppeteerRunner doesn't include error messages in the the output

### ISSUE THREAD

**Issue by steveofficer** [Zaid-Ajaj/Fable.Mocha#42]
Currently MochaPuppeteerRunner displays the tests which have failed but it doesn't include any failure messages.
On a developer machine you can work around it by manually launching a browser and looking at the page to see the messages, but on build machines it's useful to be able to get a hint as to what went wrong written to the logs.

It would be really helpful if rather than just displaying `X MyCoolComponent / does super cool thing`

It instead showed:

```
X MyCoolComponent / does super cool thing
   Expected: "This is cool"
   Actual: "Not good"
   Message: "It should tell the user when the cool thing happens"
```

**Comment by Zaid-Ajaj** [comment]
Resolved as of Fable.MochaPuppeteerRunner v1.5
