### ISSUE TITLE
Add support to run Fable.MochaPuppeteerRunner inside a docker container

### ISSUE THREAD

**Issue by steveofficer** [Zaid-Ajaj/Fable.Mocha#45]
When attempting to run tests inside a linux docker container such as `mcr.microsoft.com/dotnet/sdk:3.1` puppeteer fails to launch the process.

According to issues such as https://github.com/hardkoded/puppeteer-sharp/issues/1180 the BrowserFetcher does not include all the required dependencies required to start the browser, and so a puppeteer recipe needs to be followed.

Because Chrome is then getting baked into the image, there is no need to use the `BrowserFetcher`, and the `LauncherOptions` no longer needs `ExecutablePath` to be specified as the recipe provides an alternate means for this to be acquired. 
Additionally, `LaunchOptions` requires the inclusion of `Args = new[] { "--no-sandbox" }` 

It would be extremely useful to have a version of `runTests` that supports the above mentioned changes so that the tests are able to run inside of a docker container.

**Comment by steveofficer** [comment]
There is more detailed and authoritative documentation available at: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker

**Comment by Zaid-Ajaj** [comment]
Resolved as of Fable.MochaPuppeteerRunner v1.5
