### ISSUE TITLE
⚠ Failing async tests are not getting reported

### ISSUE THREAD

**Issue by pkese** [Zaid-Ajaj/Fable.Mocha#64]
I'm seeing a weird situation of failing async test not getting reported.

Everything is checked green and all tests pass even though one of tests is supposed to fail  
(it does fail on proper dotnet, just not when run through Node.js).

A repro repository with the code is available here: https://github.com/pkese/MochaRepro/

My test code is:
```fsharp
module Tests

open Fable.Mocha

let arithmeticTests =
    testList "Arithmetic tests" [

        testCase "plus works" <| fun () ->
            Expect.equal (1 + 1) 2 "plus"

        testCase  "Test for falsehood" <| fun () ->
            Expect.isFalse (1 = 2) "false"

        testCaseAsync "Test async code" <| async {
            let! x = async { return 21 }
            let answer = x * 2
            Expect.equal 42 answer "async"
        }

        testCaseAsync "This should have failed" <| async {
            let! one = async { return 1 }
            let two = 2
            Expect.equal one two "async"
        }
    ]

Mocha.runTests arithmeticTests |> ignore
```
and the result is:
```
 Arithmetic tests
    ✔ plus works
    ✔ Test for falsehood
    ✔ Test async code
    ✔ This should have failed
```
The last test should have failed.

**Comment by Zaid-Ajaj** [comment]
Hi @pkese thanks for opening the issue! this looks a serious issue. I'll have a look ASAP. First thing that comes to mind, are you using the npm version of mocha that `Fable.Mocha` binds to? i.e. when you `femto ./src` do you get any errors reported? It could be that you are using a more recent `mocha` library version that isn't compatible with `Fable.Mocha`.

**Comment by pkese** [comment]
I'm seeing same results both with mocha=10.2.0 or mocha=8.3.2.

It could be a problem with Fable compiler though.

Since I can't get Fable 3.7.20 to work (it just hangs during compile), I'm using fable=4.0.0-theta-018. Maybe there's something wrong with that.

Thanks a lot for your attention and help.

**Comment by pkese** [comment]
I have found a solution for this problem (see pull request above),  
but the AppVeyor build appears to be failing (reasons for build failure exceed my understanding).

My tests are now working correctly with both mocha=8.3.2 and mocha=10.2.0.

**Comment by pkese** [comment]
I'm assuming the reason for failing build - "timeout exceeded" - is that Fable 3.7.x nowadays just hangs during compile on recent versions of dotnet.

**Comment by pkese** [comment]
@Zaid-Ajaj is there any chance you could help with build issue?

**Comment by Zaid-Ajaj** [comment]
Fixed as of Fable.Mocha v2.1.6 🚀 sorry about the build failures, it's been a while since I touched the project and I needed to update it. 

> Since I can't get Fable 3.7.20 to work (it just hangs during compile), I'm using fable=4.0.0-theta-018. Maybe there's something wrong with that.

That's because Fable v3.x doesn't work with dotnet sdk v7 so you need a `global.json` file with this content:
```json
{
    "sdk": {
        "version": "6.0.400",
        "rollForward": "latestMinor"
    }
}
```
This ensures that we are using dotnet v6 to compile the project.

**Comment by Zaid-Ajaj** [comment]
The build is now running correctly in CI and you can run it locally as well:
```bash
dotnet run --project ./build/Build.fsproj -- nodejs-test
dotnet run --project ./build/Build.fsproj -- dotnet-test
dotnet run --project ./build/Build.fsproj -- headless-test
```
