### ISSUE TITLE
Add testCasePromise

### ISSUE THREAD

**Issue by forki** [Zaid-Ajaj/Fable.Mocha#9]
Is there a way to do testCasePromise instead of async { }

**Comment by Zaid-Ajaj** [comment]
It is really simple, `testCaseAsync`  expects `Async<unit>` as the last parameter. Use `Async.AwaitPromise` on `Promise<unit>` and give that to `testCaseAsync`. I haven't tested it but this should work:
```fs
let testCasePromise testName promise = 
  testCaseAsync testName (Async.AwaitPromise promise)
```
> Maybe you need to `open Fable.Core` to make `AwaitPromise` available but I am not sure

I am not sure it is a good idea to add this to the library as it will break compatibility with Expecto's API

**Comment by Zaid-Ajaj** [comment]
See these [tests from Fable.Redis](https://github.com/whitetigle/fable-redis/blob/master/tests/Tests.fs) for reference

**Comment by forki** [comment]
Thanks. Good enough for me.

Zaid Ajaj <notifications@github.com> schrieb am Mi., 6. Nov. 2019, 15:59:
